[package]
name = "ts-node"
version = "0.1.0"
edition = "2021"

[lib]
name = "ffi"
crate-type=["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
